name: Build and deploy ASP.Net Core app to Azure Web App - JamSpot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build JamSpot/JamSpotApp/JamSpotApp.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish JamSpot/JamSpotApp/JamSpotApp.csproj -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 304a9c07-fe1b-4d2a-8bf2-d103078aecc4
          tenant-id: 4a06d40c-e447-42be-baef-dd0421ed10bd
          subscription-id: 7e3ededd-c764-4f16-b516-e5b040ff83ad

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'JamSpot'
          slot-name: 'Production'
          package: ./publish
